src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 60)]
    #[Assert\NotBlank(message: "Le nom du produit ne peut pas être vide")]
    private $nom;

    #[ORM\ManyToOne(targetEntity: Categorie::class, inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: false)]
    private $type_categorie;

    #[ORM\Column(type: 'float')]
    #[Assert\NotBlank(message: "Le prix ne peut pas être vide")]
    #[Assert\Positive(message: "Le prix doit être supérieur à zéro mais là, il vaut {{ value }}")]
    private $prix_unitaire;

    #[ORM\Column(type: 'boolean')]
    private $disponibilite;

    #[ORM\OneToOne(mappedBy: 'id_produit', targetEntity: Media::class)]
    private $media;

    #[ORM\Column(type: 'text')]
    #[Assert\NotBlank(message: "La description du produit ne peut pas être vide")]
    private $description;

    #[ORM\Column(type: 'string', length: 70)]
    #[Assert\NotBlank(message: "L'interprète ne peut pas être vide")]
    private $interprete;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getTypeCategorie(): ?Categorie
    {
        return $this->type_categorie;
    }

    public function setTypeCategorie(?Categorie $type_categorie): self
    {
        $this->type_categorie = $type_categorie;

        return $this;
    }

    public function getPrixUnitaire(): ?float
    {
        return $this->prix_unitaire;
    }

    public function setPrixUnitaire(float $prix_unitaire): self
    {
        $this->prix_unitaire = $prix_unitaire;

        return $this;
    }

    public function getDisponibilite(): ?bool
    {
        return $this->disponibilite;
    }

    public function setDisponibilite(bool $disponibilite): self
    {
        $this->disponibilite = $disponibilite;

        return $this;
    }


    public function getMedia(): Media
    {
        return $this->media;
    }

    public function setMedia(Media $media)
    {
        $this->media = $media;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description2): self
    {
        $this->description = $description2;

        return $this;
    }

    public function getInterprete(): ?string
    {
        return $this->interprete;
    }

    public function setInterprete(?string $interprete): self
    {
        $this->interprete = $interprete;

        return $this;
    }

    public function __toString()
    {
        return $this->nom;
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Media;
use App\Entity\Produit;
use App\Repository\ProduitRepository;
use App\Repository\CategorieRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\Validator\Validator\ValidatorInterface;

#[Route('/produit')]
class ProduitController extends AbstractController
{
    #[Route('/', name: 'produit_index', methods: ['GET'])]
    #[IsGranted("ROLE_ADMIN")]
    public function index(ProduitRepository $produitRepository, CategorieRepository $categorieRepository): Response
    {

        return $this->render('produit/index.html.twig', [
            'produits' => $produitRepository->findAll(),
            'categories' => $categorieRepository->findAll()
        ]);
    }

    #[Route('/new', name: 'produit_new', methods: ['GET', 'POST'])]
    #[IsGranted("ROLE_ADMIN")]
    public function new(Request $request, EntityManagerInterface $entityManager, ValidatorInterface $validator, CategorieRepository $categorieRepository): Response
    {
        $produit = new Produit();
        $validation_produit = [];

        if ($request->getMethod() === "POST"){
            $categorie = $categorieRepository->findOneBy(["nom" => $request->request->get('type_categorie')]);

            $description = $request->request->get("description");

            $produit->setDescription(trim($description));
            $produit->setInterprete($request->request->get("interprete"));
            $produit->setNom($request->request->get("nom"));

            if (is_numeric($request->request->get("prix"))){
                $produit->setPrixUnitaire($request->request->get("prix"));
            }

            $produit->setTypeCategorie($categorie);
            $produit->setDisponibilite($request->request->get("disponibilite") == "dispo" ? true : false );

            $media = new Media();
            $media->setAlt($request->request->get("alt"));
            $media->setSource($request->request->get("source"));
            $media->setIdProduit($produit);
            $produit->setMedia($media);

            $validation_produit = $validator->validate($produit);
            $validation_produit->addAll($validator->validate($media));

            if (count($validation_produit) == 0 ){
                $entityManager->persist($produit);
                $entityManager->persist($media);
                $entityManager->flush();

                return $this->redirectToRoute('produit_index', [], Response::HTTP_SEE_OTHER);
            }
        }

        return $this->render('produit/form.html.twig', [
            'errors' => $validation_produit,
            'produit' => $produit,
            'categories' => $categorieRepository->findAll()
        ]);
    }

    #[Route('/{id}', name: 'produit_show', methods: ['GET'])]
    public function show(Produit $produit, CategorieRepository $categorieRepository): Response
    {

        return $this->render('produit/show.html.twig', [
            'produit' => $produit,
            'categories' => $categorieRepository->findAll()
        ]);
    }

    #[Route('/{id}/edit', name: 'produit_edit', methods: ['GET', 'POST'])]
    #[IsGranted("ROLE_ADMIN")]
    public function edit(Request $request, Produit $produit, EntityManagerInterface $entityManager, CategorieRepository $categorieRepository): Response
    {

        if ($request->getMethod() === "POST"){
            $categorie = $categorieRepository->find($request->request->get('type_categorie'));

            $produit->setDescription($request->request->get("description"));
            $produit->setInterprete($request->request->get("interprete"));
            $produit->setNom($request->request->get("nom"));
            $produit->setPrixUnitaire($request->request->get("prix"));
            $produit->setTypeCategorie($categorie);
            $produit->setDisponibilite($request->request->get("disponibilite") == "dispo" ? true : false);
            
            $media = $produit->getMedia();
            $produit->getMedia()->setAlt($request->request->get("alt_" . strval($media->getId())));
            $produit->getMedia()->setSource($request->request->get("source_" . strval($media->getId())));
            $entityManager->persist($media);
            
            
            $entityManager->persist($produit);
            $entityManager->flush();
            return $this->redirectToRoute('produit_index', [], Response::HTTP_SEE_OTHER);

        }
        

        return $this->renderForm('produit/edit.html.twig', [
            'produit' => $produit,
            'categories' => $categorieRepository->findAll()
        ]);
    }

    #[Route('/{id}', name: 'produit_delete', methods: ['POST'])]
    #[IsGranted("ROLE_ADMIN")]
    public function delete(Request $request, Produit $produit, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$produit->getId(), $request->request->get('_token'))) {
            $entityManager->remove($produit->getMedia());
            $entityManager->remove($produit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('produit_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/produit/_delete_form.html.twig
<form method="post" action="{{ path('produit_delete', {'id': produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn">Delete</button>
</form>

templates/produit/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/produit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Produit{% endblock %}

{% block body %}
    <h1>Edit Produit</h1>

    <form action="/produit/{{produit.id}}/edit" method="POST">

        <p>
            <label for="nom">Nom </label>
            <input type="text" name="nom" value="{{ produit.nom }}">
        </p>

        <p>
            <label for="interprete">Interprète </label>
            <input type="text" name="interprete" value="{{produit.interprete}}">
        </p>

        <p>
            <label for="prix">Prix unitaire </label>
            <input  type="number" step="0.01" name="prix" value={{produit.PrixUnitaire}}>
        </p>

        <p>
            <label for="disponibilite">Disponibilité</label>
            <input type="checkbox" name="disponibilite" value="dispo" checked>
        </p>

        <p>
            <label for="description">Description </label>
            <textarea name="description" rows="12" cols="100" > "{{produit.description }}"</textarea>
        </p>

        <p>
            <label for="code_postal">Catégorie </label>
            <select name="type_categorie">
                {% for categorie in categories %}
                    {% if categorie.nom == produit.TypeCategorie.nom %}
                        <option value={{ categorie.id }} selected>{{ categorie.nom }}</option>
                    {% else %}
                        <option value={{ categorie.id }}>{{ categorie.nom }}</option>
                    {% endif %}
                {% endfor %}
            </select>
        </p>

        <p>
            <label for="source">Source de l'image </label>
            <input type="text" name="source_{{produit.media.id}}" value="{{produit.media.source}}">
        </p>

        <p>
            <label for="alt">Texte alternatif de l'image </label>
            <input type="text" name="alt_{{produit.media.id}}" value="{{produit.media.alt}}">
        </p>

        <input type="submit" value="Save"/>

    </form>

    <a href="{{ path('produit_index') }}">back to list</a>

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}

templates/produit/form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout de produit{% endblock %}

{% block body %}

    {% for error in errors %}
        <p> {{error.message }} </p>
    {% endfor %}

    <form action="/produit/new" method="POST">

        <p>
            <label for="nom">Nom </label>
            <input type="text" name="nom">
        </p>

        <p>
            <label for="interprete">Interprète </label>
            <input type="text" name="interprete" >
        </p>

        <p>
            <label for="prix">Prix unitaire </label>
            <input  type="number" step="0.01" name="prix" >
        </p>

        <p>
            <label for="disponibilite">Disponibilité</label>
            <input type="checkbox" name="disponibilite" value="dispo">
        </p>

        <p>
            <label for="description">Description </label>
            <textarea name="description" > </textarea>
        </p>

        <p>
            <label for="code_postal">Catégorie </label>
            <select name="type_categorie">
                {% for categorie in categories %}
                    <option value={{ categorie.nom }}>{{ categorie.nom }}</option>
                {% endfor %}
            </select>
        </p>

        <p>
            <label for="source">Source de l'image </label>
            <input type="text" name="source" >
        </p>

        <p>
            <label for="alt">Texte alternatif de l'image </label>
            <input type="text" name="alt" >
        </p>

        <input type="submit" value="Save"/>

    </form>

    <a href="/produit/">Voir la liste des produits</a>

{% endblock %}

templates/produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit index{% endblock %}

{% block stylesheets %}
        <link rel="stylesheet" href="/css/admin_all_products.css" />
{% endblock %}

{% block body %}
    <h1>Produit index</h1>

    <table id="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prix_unitaire</th>
                <th>Disponibilite</th>
                <th>Type categorie </th>
                <th>Interprète </th>
                <th>Source des medias </th>
                <th>Texte alternatif du media </th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for produit in produits %}
            <tr>
                <td>{{ produit.id }}</td>
                <td>{{ produit.nom }}</td>
                <td>{{ produit.prixUnitaire }} €</td>
                <td>{{ produit.disponibilite ? 'Yes' : 'No' }}</td>
                <td>{{ produit.TypeCategorie }}</td>
                <td>{{ produit.interprete }}</td>

                <td class="media_source"><a href="{{produit.media.source}}">{{produit.media.source}}</a></td>

                <td>{{produit.media.alt}}</td>
                
                <td class="action_cell">
                    <div class="action_div">
                        <a href="{{ path('produit_show', {'id': produit.id}) }}" >show</a>
                        <a href="{{ path('produit_edit', {'id': produit.id}) }}" >edit</a>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    
    <div id="lien_creation">
        <a href="{{ path('produit_new') }}">Create new</a>
    </div>
{% endblock %}

templates/produit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Produit{% endblock %}

{% block body %}
    <h1>Create new Produit</h1>

    {{ include('produit/_form.html.twig') }}

    <a href="{{ path('produit_index') }}">back to list</a>
{% endblock %}

templates/produit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="/css/product.css" >
{% endblock %}

{% block body %}

    <div id="block_produit">

        <div id="photo">
                <img src={{ produit.media.source }} alt={{produit.media.alt}} class="img_produits"/>
        </div>

        <div id="description">

            <h2>{{ produit.nom }}</h2>
            <p id="prix">{{ produit.prixUnitaire }} €</p>
            <p>{{ produit.description}}</p>

            <button><a href="/panier/add?id_produit={{produit.id}}">Ajouter au panier </a></button>

        </div>

    </div>
{% endblock %}